name: "run-kube-score"
description: "Installs and runs kube-score"
inputs:
  manifests_path:
    description: "Path to the Kubernetes manifests for a dedicated environment"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install kube-score
      shell: bash
      run: curl -sSL -o kube-score "https://github.com/zegl/kube-score/releases/download/v1.20.0/kube-score_1.20.0_linux_amd64"
    - name: Run kube-score
      shell: bash
      run: |
          chmod +x kube-score
          kustomize build ${{ inputs.manifests_path }} --enable-helm | ./kube-score score -
